### ISSUE TITLE
Suggestion: don't color variable declarations differently

### ISSUE THREAD

**Issue by matklad** [drzix/hc-zenburn-vscode#1]
Hey, I've noticed that your theme sets a different color for variable declarations vs variable usages. This is how Emacs zenburn works, but I'd argue that this is not the right approach in light of semantic highlighting :0)

For semantic highlighting, the rule of thumb is "color the references and declarations the same". So, for example, it would make sense to color locals, paams and fields different, so that at a glance you can say if a thing is a local or not.

For example, in Palse Fire I use dedicated colors for fields (I don't distinguish between params and locals, but that should be possible (though we need to change rust-analyzer to emit `variable.param` type)):

![image](https://user-images.githubusercontent.com/1711539/87201269-86f66d80-c2fe-11ea-8b5d-9b68b607c153.png)

Here's the same snippet in hc-zenburn, note now `new_status` changes color between definition and usage.

![image](https://user-images.githubusercontent.com/1711539/87201236-780fbb00-c2fe-11ea-81a3-4c09535e349a.png)

I think the reason why original Zenburn emacs works that way is mostly historical -- you can distinguish declaration vs usage using regular expressions, but you can't figure out what the name refers to. 

For the reference, here's the full set of semantic color customizations pale fire does:

https://github.com/matklad/pale-fire/blob/4b99679387bab61554a6cc4434f39593fbb03543/themes/Pale%20Fire-color-theme.json#L13-L49

**Comment by drzix** [comment]
Hi, Aleksey.
Thanks for your detailed suggestion :)

This theme was originally meant to replicate the Emacs one. So I wasn't very suspicious of the way it displays color.
However, I noticed the need to modify this theme in moderation as your suggestions seemed sufficiently convincing.
I'll apply it in the next patch.

**Comment by matklad** [comment]
>though we need to change rust-analyzer to emit variable.param type

Fixed in:

https://github.com/rust-analyzer/rust-analyzer/pull/5314

there's existing `parameter` semantic token type for this in LSP

**Comment by drzix** [comment]
It's been a long time!

I applied your suggestions (including #2) to the 0.3.0 release.
Your pale fire repo and the set of semantic color customizations is really helpful for me.
Also, I was very surprised that your rust-analyzer is now significantly awesome.

I appreciate your contribution to the human race 👍
