### ISSUE TITLE
Consider giving different colors for different declarations

### ISSUE THREAD

**Issue by matklad** [drzix/hc-zenburn-vscode#2]
It looks like hc-zenburn uses a single color for all type-y things:

![image](https://user-images.githubusercontent.com/1711539/87202859-b78bd680-c301-11ea-8a09-d031d783f1cc.png)

I suggest using different colors for traits and type parameters. Here's how the same example looks with Pale Fire:

![image](https://user-images.githubusercontent.com/1711539/87202929-d8ecc280-c301-11ea-9a5a-7886c22eb46d.png)

I find it useful to distinguish between (enums,structs,unions), variants, traits, and type parameters. And some color variance is nice by itself :-)

Meta: I really like hc-zenburn-vscode, but I also am a die-hard fan of strong semantic highlighting. If you also feel that we should expose more semantic info (like #1 and this issue proposes), I would be tempted to just abandon Pale Fire (despite the name being even more perfect than that of zenburn) in favor of hc-zenburn :)

**Comment by drzix** [comment]
Thanks again!

**Comment by drzix** [comment]
Again, thanks!
